#!/usr/bin/env python
from PyQt5 import QtWidgets
import sys

from slickpicker import QColorEdit

app=QtWidgets.QApplication(sys.argv)
picker=QColorEdit()
picker.show()
retcode = app.exec()
print(picker.lineEdit.text())
exit(retcode)
