#!/usr/bin/env python
from PyQt4 import QtGui
import sys

from slickpicker import QColorEdit

app=QtGui.QApplication(sys.argv)
picker=QColorEdit()
picker.show()
retcode = app.exec()
print(picker.colorEdit.text())
exit(retcode)
